### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Braingenius2** [mhnazary/Temperature-Converter#1]
Good job! 👏 Your code looks quite good overall. Here are a few suggestions to further enhance it:

   - Add comments: Consider adding comments to describe the purpose and functionality of each section of code. This will make it easier for others (and yourself) to understand the code in the future.

  - Use const for variables that don't need reassignment: Since you're not reassigning values to inputValue, placeholderValue, result, c, f, convertBtn, resetBtn, and changeBtn, you can use const instead of let to make it clear that these variables are not intended to be reassigned. [link to code](https://github.com/mhnazary/Temperature-Converter/blob/ab3b7260a9baceabd5ae2292fd417fb228cee401/js/script.js#L2)
 
By @Braingenius2 and the team 👍

**Comment by mhnazary** [comment]
> Good job! 👏 Your code looks quite good overall. Here are a few suggestions to further enhance it:
> 
> * Add comments: Consider adding comments to describe the purpose and functionality of each section of code. This will make it easier for others (and yourself) to understand the code in the future.
> * Use const for variables that don't need reassignment: Since you're not reassigning values to inputValue, placeholderValue, result, c, f, convertBtn, resetBtn, and changeBtn, you can use const instead of let to make it clear that these variables are not intended to be reassigned. [link to code](https://github.com/mhnazary/Temperature-Converter/blob/ab3b7260a9baceabd5ae2292fd417fb228cee401/js/script.js#L2)
> 
> By @Braingenius2 and the team 👍

Thank you for your suggestion. I am going to follow that.
