### ISSUE TITLE
Code Review Exercise

### ISSUE THREAD

**Issue by JuanDBta** [mhnazary/Temperature-Converter#2]
Hey Hossain! Pretty cool the app you have made...there is nothing to say about the code in JS, is done with ES6 best practices.  The only thing I would suggest is to improve the styling, you can put a awsome background.  Thanks for sharing your project!

**Comment by mhnazary** [comment]
> Hey Hossain! Pretty cool the app you have made...there is nothing to say about the code in JS, is done with ES6 best practices. The only thing I would suggest is to improve the styling, you can put a awsome background. Thanks for sharing your project!
